# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-26 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('hobbies', models.CharField(default='', max_length=1000)),
                ('bio', models.CharField(default='', max_length=1000)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('github', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
