# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170629_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='Person',
        ),
    ]
