# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-30 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_person_mantra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
